Backup2/Models/Restaurant.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace OdeToFood.Models
{
    public class Restaurant
    {
        public virtual int ID { get; set; }
        public virtual string Name { get; set; }
        public virtual Address Address { get; set; }
        public virtual ICollection<Review> Reviews { get; set; }
    }
}

Backup2/Controllers/RestaurantController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OdeToFood.Models;

namespace OdeToFood.Controllers
{
    public class RestaurantController : Controller
    {
        //
        // GET: /Restaurant/

        public ActionResult Index(string state)
        {

            ViewBag.States = _db.Restaurants.Select(r => r.Address.State).Distinct();

            var model =
                _db.Restaurants
                   .OrderByDescending(r => r.Address.City)
                   .Where(r => r.Address.State == state || (state == null));             

            return View(model);
        }

        public ActionResult Details(int id)
        {
            var model = _db.Restaurants.Single(r => r.ID == id);

            return View(model);
        }
       
        OdeToFoodDB _db = new OdeToFoodDB();
    }
}

Backup2/Controllers/ReviewsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using OdeToFood.Models;
using OdeToFood.Queries;
using System.Data;
using Microsoft.Security.Application;

namespace OdeToFood.Controllers
{
    public class ReviewsController : Controller
    {
        OdeToFoodDB _db = new OdeToFoodDB();

        //
        // GET: /Reviews/

        public ActionResult Index()
        {
            var model = _db.Reviews.FindTheLatest(3);
            return View(model);
        }

        [ChildActionOnly]
        public ActionResult BestReview()
        {
            var model = _db.Reviews.FindTheBest();
            return PartialView("_Review", model);
        }

        //
        // GET: /Reviews/Details/5

        public ActionResult Details(int id)
        {
            return View();
        }

        //
        // GET: /Reviews/Create

        public ActionResult Create()
        {
            return View(new Review());
        } 

        //
        // POST: /Reviews/Create

        [HttpPost]
        public ActionResult Create(int restaurantID, Review newReview)
        {
            try
            {
                var restaurant = _db.Restaurants.Single(r => r.ID == restaurantID);
                restaurant.Reviews.Add(newReview);
                _db.SaveChanges();

                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }        
        //
        // GET: /Reviews/Edit/5
        public ActionResult Edit(int id)
        {
            var review = _db.Reviews.FindById(id);
            return View(review);
        }

        //
        // POST: /Reviews/Edit/5

        [HttpPost]
        [ValidateAntiForgeryToken]  
        public ActionResult Edit(Review review)
        {            
            if (ModelState.IsValid)
            {
                review.Body = Sanitizer.GetSafeHtmlFragment(review.Body);
                _db.Entry(review).State = EntityState.Modified;
                _db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(review);
        }       

        //
        // GET: /Reviews/Delete/5
 
        public ActionResult Delete(int id)
        {
            return View();
        }

        //
        // POST: /Reviews/Delete/5

        [HttpPost]
        public ActionResult Delete(int id, FormCollection collection)
        {
            try
            {
                // TODO: Add delete logic here
 
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }
        }
    }
}

Backup2/Views/Restaurant/Details.cshtml
@model OdeToFood.Models.Restaurant

@{
    ViewBag.Title = "Details";
}

<fieldset>
    <legend>Restaurant</legend>

    <div class="display-label">Name</div>
    <div class="display-field">@Model.Name</div>

    @Html.DisplayFor(model => model.Address)
    
</fieldset>
<p>
    @Html.ActionLink("Edit", "Edit", new { id=Model.ID }) |
    @Html.ActionLink("Back to List", "Index")
</p>

<h2>Reviews</h2>

@foreach (var review in Model.Reviews)
{
    @Html.Partial("_Review", review)
}

@Html.ActionLink("Create a new review", "Create", "Reviews", new { restaurantID = Model.ID }, null)

Backup2/Views/Restaurant/Index.cshtml
@model IEnumerable<OdeToFood.Models.Restaurant>

@{
    ViewBag.Title = "Index";
}

<h2>Index</h2>

<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table>
    <tr>
        <th>
            Name
        </th>
        <th>
            Address
        </th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.ActionLink(item.Name, "Details", "Restaurant", new { id=item.ID} , null)
        </td>
        <td>
            @item.Address.City, @item.Address.State 
        </td>
    </tr>
}

</table>
